Resolve out of range error
unikraft/kraft pull request #82
Opened 2021-10-30 08:26 UTC by gabrielmocanu

Add a check for `out of range` error if the name of the base directory is different from the name of the application from kraft.yaml.

Fixes #80 
Signed-off-by: Gabriel Mocanu <gabi.mocanu98@gmail.com>

2022-01-22 08:41 UTC, razvand requested changes
I made some layout / wording suggestions.

2022-01-22 08:41 UTC, razvand commented on kraft/cmd/run.py
> +        if(len(binaries) == 0):
```suggestion
        if (len(binaries) == 0):
```

2022-01-22 08:41 UTC, razvand commented on kraft/cmd/run.py
> +            raise ValueError("Unikernel binary not found.(Please check that your application name is the same as directory name)")
```suggestion
            raise ValueError("Unikernel binary not found. Please check that your application name (in the kraft.yaml file) is the same as directory name.")
```

2022-01-22 08:52 UTC, StefanJum reviewed
When using `kraft up -t helloworld different-name-dir` this does not work, since the `if` on [this line](https://github.com/unikraft/kraft/blob/staging/kraft/cmd/run.py#L79) is not taken, and `target` is set [here](https://github.com/unikraft/kraft/blob/staging/kraft/cmd/run.py#L75).
Works fine with `kraft run`.

2022-03-19 08:08 UTC, closed without merging

2022-03-19 08:10 UTC, gabrielmocanu commented
I closed this PR since this one[1] fixed the issue.

[1]: https://github.com/unikraft/kraft/pull/94