util/op,plat/network: parse subprocess output as utf-8
unikraft/kraft pull request #99
Opened 2022-02-10 10:03 UTC by TheLortex

Fixes https://github.com/unikraft/kraft/issues/96

Note: the default encoding for `decode` is `UTF-8` so that's why I omitted it, but it can be made explicit if preferred.

2022-03-05 09:14 UTC, StefanJum requested changes
I think you should explicitly add the `utf-8` encoding for consistency.
It is used explicitly in the `kraft` code (e.g. [here](https://github.com/unikraft/kraft/blob/staging/kraft/config/interpolation.py#L108) and [here](https://github.com/unikraft/kraft/blob/staging/kraft/config/kconfig.py#L55)).

Otherwise looks good.

2022-03-15 15:31 UTC, TheLortex commented
Hi @StefanJum, thanks for the review. I have added the explicit `utf-8` encoding argument.

2022-03-16 10:14 UTC, StefanJum approved these changes
Looks good now!

Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2022-03-16 12:30 UTC, nderjung commented
Thanks!

2022-03-16 12:30 UTC, merged